##########################################
# 07. Dockerfile with Volume & Port
##########################################
FROM nginx:alpine
VOLUME ["/data"]
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]